enabled: true
rbac:
  create: true
defaultBackend:
  enabled: true
controller:
  service:
    enabled: true
    externalIPs:
      - 192.168.0.62
    enableHttp: true
    enableHttps: true
    healthCheckNodePort: 0
    ports:
      http: 80
      https: 443
    targetPorts:
      http: http
      https: https
    type: NodePort
