apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  externalTrafficPolicy: Cluster
  externalIPs:
  # Add your cluster ip address here:
  - 192.168.0.76
